# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6969cfc8ff2e9006b4601765f71f4f6ffb023ffabc573dfd53694589a4460816146548f96dca5a25269f193dc215894069e02ee5e1d7413f2d9c9d4c0a451e9

test:
  secret_key_base: ebd3f0033be72a9b7a29274134fa752fdc4e7d9aed2fab906ec1f67cebad1f3fc938cfcc5b2e0f2f8d0c70c1ade2f9a8528f288b4ec5ac3619f46a1a89b0ed91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
